import streamlit as st


def show():
    """Display the HeroGen landing page."""
    st.markdown(
        """
    <div style="text-align: center; padding: 40px 0 20px 0;">
        <h1 style="font-size: 3.5em; margin-bottom: 0;">📚 HeroGen</h1>
        <h2 style="color: #4ECDC4; font-weight: 400;">
            Turn Your Child Into a Reading Hero!
        </h2>
        <p style="font-size: 1.2em; color: #666; max-width: 600px; margin: 20px auto;">
            Upload a photo, pick a moral value, and our AI creates a
            personalized storybook in under 60 seconds — complete with
            illustrations, coloring pages, and a teacher's guide!
        </p>
    </div>
    """,
        unsafe_allow_html=True,
    )

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        if st.button(
            "Create Story Now",
            type="primary",
            use_container_width=True,
        ):
            st.session_state.page = "create"
            st.rerun()

    st.divider()

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("### AI Illustrations")
        st.write(
            "Beautiful watercolor-style images generated by AI, "
            "personalized for each story scene."
        )

    with col2:
        st.markdown("### Age-Adapted Text")
        st.write(
            "Story complexity automatically adjusts to your child's "
            "reading level (ages 4-8)."
        )

    with col3:
        st.markdown("### Edu-Pack Included")
        st.write(
            "Every book includes coloring pages and a teacher's "
            "discussion guide with vocabulary."
        )

    st.divider()
    st.markdown(
        """
    <div style="text-align: center; padding: 15px; color: #888;">
        <p>Trusted by parents and educators</p>
        <p>Powered by GPT-4o - DALL-E 3 - Computer Vision</p>
    </div>
    """,
        unsafe_allow_html=True,
    )