[theme]
primaryColor = "#E67E22"
backgroundColor = "#D6EAF8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2B3A4A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
